#! /usr/bin/env bash
# dependencies xorg-xbacklight

mute=$(pactl list | grep Mute: | head -n1 | cut -b7-)
volume=$(pactl list | grep Volume | head -n1 | awk {'print $5'} | cut -b-2)
xobpipe=~/.config/xob/xobpipe
# increase or decrease
value=5

# if xobpipe file don't exist then create that file
if [ ! -f "$xobpipe" ]; then
    touch $xobpipe
fi

case "$1" in
vol-up)
	# Volume Up
    pamixer -i $value
    pamixer --get-volume > $xobpipe
    theme=volume
    ;;
vol-down)
	# Volume Down
    pamixer -d $value
    pamixer --get-volume > $xobpipe
    theme=volume
    ;;
bl-up)
	# Brightness / Backlig<t up
    xbacklight -inc +$value
    xbacklight -get > $xobpipe
    theme=backlight
    ;;
bl-down)
	# Brightness / Backlig<t down
    xbacklight -dec +$value
    xbacklight -get > $xobpipe
    theme=backlight
    ;;
*)
    notify-send 'Use vol-down, vol-up, bl-up, bl-down'
    ;;
esac

#SERVICE="xob"
#if pgrep -x "$SERVICE" >/dev/null
#then
#    echo "$SERVICE is running"
#else
#	tail -f $xobpipe | xob -s $theme
#fi