#!/usr/bin/env bash

# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Run xidlehook
xidlehook \
  --not-when-fullscreen \
  --not-when-audio \
  ` #LockSreen` \
  --timer 360 \
  'xrandr --output "$PRIMARY_DISPLAY" --brightness 1; ~/.bin/lockScreen' \
  '' \
  `# Switch off` \
  --timer 120 \
  'xdg-screensaver activate' \
  '' 